version: '3.8'

services:
    dev:
        container_name: regat_api_dev
        image: regat-api-nestjs-dev:1.0.0
        build:
            context: .
            target: development
            dockerfile: ./Dockerfile
        command: npm run start:dev
        ports:
            - 3000:3000
            - 9229:9229
        networks:
            - intern-network
        volumes:
            - /usr/src/app/node_modules
        restart: unless-stopped
    prod:
        container_name: regat_api_prod
        image: sensehealth/regat:1.5.0
        build:
            context: .
            target: production
            dockerfile: ./Dockerfile
        command: npm run start:prod
        env_file:
            - .env
        ports:
            - 3000:3000
        networks:
            - intern-network
        restart: unless-stopped

networks:
    intern-network: